name: Trigger Doc Generation

on:
  push:
    branches:
      - main

jobs:
  trigger:
    name: Trigger Doc Generation
    runs-on: ubuntu-latest
    steps:
    - name: Trigger build
      run: |
        curl -X POST \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        https://api.github.com/repos/Bal7hazar/kinto-un/dispatches \
        -d '{"event_type": "build"}'
